feat(THA-1187): add cumulative protocol fee metric
ThalaLabs/thala-indexer pull request #145
Opened 2023-05-14 02:59 UTC by LawsonGraham

added a counter for both the cdp and thalaswap projects, where we aggregate net fees for protocol into `cumulative_protocol_fee`

2023-05-14 04:08 UTC, 0xbe1 approved these changes
lgtm

2023-05-14 04:08 UTC, 0xbe1 commented
@LawsonGraham can you also attach a link to the data source?

2023-05-14 05:48 UTC, 0xbe1 requested changes

2023-05-14 05:48 UTC, 0xbe1 commented on projects/mod/src/processor.ts
> +    const feeUsd = event.data_decoded.liquidation_fee.scaleDown(coinInfo.decimals).multipliedBy(priceIn);
let's not do USD, use coin unit instead

2023-05-14 05:48 UTC, 0xbe1 commented on projects/thalaswap/src/processors/base_pool.ts
> +  ctx.meter.Counter("cumulative_protocol_fee").add(feeUsd);
let's not do USD, use coin unit instead

2023-05-14 18:48 UTC, LawsonGraham commented on projects/mod/src/processor.ts
> +    const feeUsd = event.data_decoded.liquidation_fee.scaleDown(coinInfo.decimals).multipliedBy(priceIn);
in different places we are fees paid in different coins, and thus pricing / value would be different, so we couldn't simply add to one general counter unless we have some base unit like USD to count in... wdyt best way forward is?

2023-05-15 01:00 UTC, 0xbe1 commented on projects/mod/src/processor.ts
> +    const feeUsd = event.data_decoded.liquidation_fee.scaleDown(coinInfo.decimals).multipliedBy(priceIn);
imagine 2 fee events:
- 10 days ago, 1 APT fee, when 1 APT = $10
- today, 1 APT fee, when 1 APT = $8

we cannot simply add 10 + 8 = 18. instead, we should simply count 2 APT as fee

2023-05-15 01:01 UTC, LawsonGraham commented on projects/mod/src/processor.ts
> +    const feeUsd = event.data_decoded.liquidation_fee.scaleDown(coinInfo.decimals).multipliedBy(priceIn);
ah this makes total sense - so then we can record by coin, and then aggregate / sum up in USD on dapp size - how does this sound?

2023-05-15 01:02 UTC, 0xbe1 commented on projects/mod/src/processor.ts
> +    const feeUsd = event.data_decoded.liquidation_fee.scaleDown(coinInfo.decimals).multipliedBy(priceIn);
sgtm

2023-05-15 05:26 UTC, 0xbe1 approved these changes
lgtm!

2023-05-15 05:29 UTC, merged